type CountryMapping = {
  [key: string]: { country: string; code: string };
};

export const countryCodes: CountryMapping = {
  "39A": { country: "France", code: "FR" },
  "3B9": { country: "France", code: "FR" },
  "3BF": { country: "France", code: "FR" },
  "3B7": { country: "France", code: "FR" },
  "3AA": { country: "France", code: "FR" },
  "43C": { country: "United Kingdom", code: "GB" },
  "400": { country: "United Kingdom", code: "GB" },
  "407": { country: "United Kingdom", code: "GB" },
  "3E8": { country: "Germany", code: "DE" },
  "3EA": { country: "Germany", code: "DE" },
  "3EB": { country: "Germany", code: "DE" },
  "3F4": { country: "Germany", code: "DE" },
  "3F7": { country: "Germany", code: "DE" },
  "3FA": { country: "Germany", code: "DE" },
  "3FB": { country: "Germany", code: "DE" },
  "3E9": { country: "Germany", code: "DE" },
  "3F5": { country: "Germany", code: "DE" },
  "3F9": { country: "Germany", code: "DE" },
  "3F6": { country: "Germany", code: "DE" },
  "341": { country: "Spain", code: "ES" },
  "343": { country: "Spain", code: "ES" },
  "352": { country: "Spain", code: "ES" },
  "354": { country: "Spain", code: "ES" },
  "355": { country: "Spain", code: "ES" },
  "356": { country: "Spain", code: "ES" },
  "347": { country: "Spain", code: "ES" },
  "353": { country: "Spain", code: "ES" },
  "497": { country: "Portugal", code: "PT" },
  "449": { country: "Belgium", code: "BE" },
  "44F": { country: "Belgium", code: "BE" },
  "4A3": { country: "Romania", code: "RO" },
  "4B8": { country: "Turkey", code: "TR" },
  "4BA": { country: "Turkey", code: "TR" },
  "738": { country: "Israel", code: "IL" },
  "157": { country: "Russia", code: "RU" },
  "14F": { country: "Russia", code: "RU" },
  "153": { country: "Russia", code: "RU" },
  "155": { country: "Russia", code: "RU" },
  "4CA": { country: "Ireland", code: "IE" },
  "154": { country: "Russia", code: "RU" },
  AE0: { country: "United States", code: "US" },
  ADF: { country: "United States", code: "US" },
  A42: { country: "United States", code: "US" },
  A89: { country: "United States", code: "US" },
  A9D: { country: "United States", code: "US" },
  AAB: { country: "United States", code: "US" },
  AB3: { country: "United States", code: "US" },
  ABA: { country: "United States", code: "US" },
  AF4: { country: "United States", code: "US" },
  A3C: { country: "United States", code: "US" },
  AD3: { country: "United States", code: "US" },
  "320": { country: "Italy", code: "IT" },
  "33F": { country: "Italy", code: "IT" },
  ADD: { country: "United States", code: "US" },
  AE7: { country: "United States", code: "US" },
  AE6: { country: "United States", code: "US" },
  AE5: { country: "United States", code: "US" },
  AED: { country: "United States", code: "US" },
  AE4: { country: "United States", code: "US" },
  AE2: { country: "United States", code: "US" },
  AE1: { country: "United States", code: "US" },
  A96: { country: "United States", code: "US" },
  A8B: { country: "United States", code: "US" },
  A6D: { country: "United States", code: "US" },
  A36: { country: "United States", code: "US" },
  A2E: { country: "United States", code: "US" },
  A09: { country: "United States", code: "US" },
  AAA: { country: "United States", code: "US" },
  AA7: { country: "United States", code: "US" },
  ADC: { country: "United States", code: "US" },
  A9A: { country: "United States", code: "US" },
  "800": { country: "India", code: "IN" },
  "801": { country: "India", code: "IN" },
  "70C": { country: "Oman", code: "OM" },
  "706": { country: "Kuwait", code: "KW" },
  "894": { country: "Bahrain", code: "BH" },
  "505": { country: "Slovakia", code: "SK" },
  "451": { country: "Bulgaria", code: "BG" },
  "498": { country: "Czechia", code: "CZ" },
  "481": { country: "Netherlands", code: "NL" },
  "480": { country: "Netherlands", code: "NL" },
  "485": { country: "Netherlands", code: "NL" },
  "0AC": { country: "Columbia", code: "CO" },
  "0D0": { country: "Mexico", code: "MX" },
  "0D8": { country: "Venezuela", code: "VE" },
  E84: { country: "Ecuador", code: "EC" },
  E49: { country: "Brazil", code: "BR" },
  E47: { country: "Brazil", code: "BR" },
  E48: { country: "Brazil", code: "BR" },
  E40: { country: "Brazil", code: "BR" },
  E14: { country: "Argentina", code: "AR" },
  C2C: { country: "Canada", code: "CA" },
  C2B: { country: "Canada", code: "CA" },
  C2A: { country: "Canada", code: "CA" },
  "896": { country: "United Arab Emirates", code: "AE" },
  "710": { country: "Saudi Arabia", code: "SA" },
  "711": { country: "Saudi Arabia", code: "SA" },
  "717": { country: "Saudi Arabia", code: "SA" },
  "732": { country: "Iran", code: "IR" },
  "50F": { country: "Ukraine", code: "UA" },
  "506": { country: "Slovenia", code: "SI" },
  "4CC": { country: "Iceland", code: "IS" },
  "4B7": { country: "Switzerland", code: "CH" },
  "4A8": { country: "Sweden", code: "SE" },
  "48D": { country: "Poland", code: "PL" },
  "478": { country: "Norway", code: "NO" },
  "477": { country: "Hungary", code: "HU" },
  "467": { country: "Finland", code: "FI" },
  "447": { country: "Austria", code: "AT" },
  "0C4": { country: "Dominican Republic", code: "DO" },
  "0B4": { country: "Guatemala", code: "GT" },
  "090": { country: "Angola", code: "AO" },
  "06A": { country: "Qatar", code: "QA" },
  "45F": { country: "Denmark", code: "DK" },
  "020": { country: "Morocco", code: "MA" },
  "4D0": { country: "Luxembourg", code: "LU" },
  "044": { country: "Ghana", code: "GH" },
  "743": { country: "Jordan", code: "JO" },
  E88: { country: "Paraguay", code: "PY" },
  "0C2": { country: "Panama", code: "PA" },
  "0BA": { country: "Honduras", code: "HN" },
  "8A0": { country: "Indonesia", code: "ID" },
  E20: { country: "Argentina", code: "AR" },
  "516": { country: "Montenegro", code: "ME" },
  "880": { country: "Thailand", code: "TH" },
  "883": { country: "Thailand", code: "TH" },
  "881": { country: "Thailand", code: "TH" },
  "884": { country: "Thailand", code: "TH" },
  "7CF": { country: "Australia", code: "AU" },
  C87: { country: "New Zealand", code: "NZ" },
  "010": { country: "Egypt", code: "EG" },
  "750": { country: "Malaysia", code: "MY" },
  "503": { country: "Lithuania", code: "LT" },
  "094": { country: "Benin", code: "BJ" },
  E90: { country: "Uruguay", code: "UY" },
  468: { country: "Greece", code: "GR" },
  "46F": { country: "Greece", code: "GR" },
  "758": { country: "Philippines", code: "PH" },
  "87C": { country: "Japan", code: "JP" },
  "762": { country: "Pakistan", code: "PK" },
  "507": { country: "Uzbekistan", code: "UZ" },
  "0A4": { country: "Algeria", code: "DZ" },
  "038": { country: "Cote d'Ivoire", code: "CI" },
  "683": { country: "Kazakhstan", code: "KZ" },
  "018": { country: "Libya", code: "LY" },
  "4D2": { country: "Malta", code: "MT" },
};
