type CountryMapping = {
  [key: string]: string;
};

type AircraftTypes = "Fixed-wing" | "Rotary-wing" | "Unknown";

type AircraftMapping = {
  [key: string]: { name: string; type: AircraftTypes };
};

const countryCodes: CountryMapping = {
  "39A": "France",
  "3B9": "France",
  "3BF": "France",
  "3B7": "France",
  "3AA": "France",
  "43C": "United Kingdom",
  "400": "United Kingdom",
  "407": "United Kingdom",
  "3E8": "Germany",
  "3EA": "Germany",
  "3EB": "Germany",
  "3F4": "Germany",
  "3F7": "Germany",
  "3FA": "Germany",
  "3FB": "Germany",
  "3E9": "Germany",
  "3F5": "Germany",
  "3F9": "Germany",
  "352": "Spain",
  "354": "Spain",
  "355": "Spain",
  "356": "Spain",
  "347": "Spain",
  "353": "Spain",
  "497": "Portugal",
  "449": "Belgium",
  "44F": "Belgium",
  "4A3": "Romania",
  "4B8": "Turkey",
  "738": "Israel",
  "157": "Russia",
  "14F": "Russia",
  "153": "Russia",
  "155": "Russia",
  "4CA": "Ireland",
  AE0: "USA",
  ADF: "USA",
  A42: "USA",
  A89: "USA",
  A9D: "USA",
  AAB: "USA",
  AB3: "USA",
  ABA: "USA",
  AF4: "USA",
  "320": "Italy",
  "33F": "Italy",
  ADD: "USA",
  AE7: "USA",
  AE6: "USA",
  AE5: "USA",
  AED: "USA",
  AE4: "USA",
  AE2: "USA",
  AE1: "USA",
  A96: "USA",
  A8B: "USA",
  A6D: "USA",
  A36: "USA",
  A2E: "USA",
  A09: "USA",
  AAA: "USA",
  AA7: "USA",
  ADC: "USA",
  "800": "India",
  "70C": "Oman",
  "706": "Kuwait",
  "894": "Bahrain",
  "505": "Slovakia",
  "451": "Bulgaria",
  "498": "Czechia",
  "481": "Netherlands",
  "480": "Netherlands",
  "485": "NetherLands",
  "0AC": "Columbia",
  "0D0": "Mexico",
  "0D8": "Venezuela",
  E84: "Ecuador",
  E49: "Brazil",
  E48: "Brazil",
  E40: "Brazil",
  E14: "Argentina",
  C2C: "Canada",
  C2B: "Canada",
  C2A: "Canada",
  "896": "United Arab Emirates",
  "710": "Saudi Arabia",
  "732": "Iran",
  "50F": "Ukraine",
  "506": "Slovenia",
  "4CC": "Iceland",
  "4B7": "Switzerland",
  "4A8": "Sweden",
  "48D": "Poland",
  "478": "Norway",
  "477": "Hungary",
  "467": "Finland",
  "447": "Austria",
  "0C4": "Dominican Republic",
  "0B4": "Guatemala",
  "090": "Angola",
  "06A": "Qatar",
  "45F": "Denmark",
  "020": "Morocco",
  "4D0": "Luxembourg",
  "044": "Ghana",
  "743": "Jordan",
  E88: "Paraguay",
  "0C2": "Panama",
  "0BA": "Honduras",
  "8A0": "Indonesia",
  E20: "Argentina",
  "516": "Montenegro",
  "881": "Thailand",
  "884": "Thailand",
  "7CF": "Australia",
  C87: "New Zealand",
  "010": "Egypt",
  "750": "Malaysia",
  "503": "Lithuania",
  "094": "Benin",
  E90: "Uruguay",
  468: "Greece",
  "758": "Philippines",
  "87C": "Japan",

  // "34": "Spain",
};

const aircraftTypes: AircraftMapping = {
  EUFI: { name: "EUROFIGHTER 2000", type: "Fixed-wing" },
  B350: { name: "BEECHCRAFT Super King Air 350", type: "Fixed-wing" },
  K35R: { name: "BOEING KC-135R/T Stratotanker", type: "Fixed-wing" },
  E50P: { name: "EMBRAER EMB-500 Phenom 100", type: "Fixed-wing" },
  PC9: { name: "PILATUS PC-9 Hudournik", type: "Fixed-wing" },
  EC45: { name: "AIRBUS HELICOPTERS EC-145", type: "Rotary-wing" },
  EH10: { name: "AGUSTA WESTLAND EH-101 Merlin", type: "Rotary-wing" },
  A400: { name: "AIRBUS A-400M Atlas", type: "Fixed-wing" },
  H64: { name: "MCDONNELL DOUGLAS AH-64 Apache", type: "Rotary-wing" },
  LYNX: { name: "AGUSTAWESTLAND AW-159 Super Lynx", type: "Rotary-wing" },
  B52: { name: "Boeing B-52H Stratofortress", type: "Fixed-wing" },
  G12T: { name: "GROB G-120TP", type: "Fixed-wing" },
  H47: { name: "BOEING-VERTOL CH-47 Chinook", type: "Rotary-wing" },
  C17: { name: "Boeing C-17A Globemaster III", type: "Fixed-wing" },
  C295: { name: "CASA C-295 Persuader", type: "Fixed-wing" },
  CL60: { name: "BOMBARDIER CL-600 Challenger", type: "Fixed-wing" },
  C130: { name: "LOCKHEED C-130 Hercules", type: "Fixed-wing" },
  IL76: { name: "ILYUSHIN Il-76/82", type: "Fixed-wing" },
  GLF5: { name: "GULFSTREAM 5", type: "Fixed-wing" },
  TWR: { name: "TWR", type: "Fixed-wing" },
  A332: { name: "AIRBUS A-330-200", type: "Fixed-wing" },
  A139: { name: "AGUSTA AW-139", type: "Rotary-wing" },
  E3TF: { name: "BOEING E-3 Sentry (TF33)", type: "Fixed-wing" },
  P8: { name: "BOEING P-8 Poseidon", type: "Fixed-wing" },
  AT76: { name: "ATR-72-600", type: "Fixed-wing" },
  R135: { name: "Boeing RC-135S Cobra Ball", type: "Fixed-wing" },
  B762: { name: "BOEING 767-200", type: "Fixed-wing" },
  B77W: { name: "BOEING 777-300ER", type: "Fixed-wing" },
  A148: { name: "ANTONOV An-148", type: "Fixed-wing" },
  EC35: { name: "AIRBUS HELICOPTERS EC-135/635", type: "Rotary-wing" },
  GLEX: { name: "BOMBARDIER BD-700 Global 6000/6500", type: "Fixed-wing" },
  F900: { name: "DASSAULT Falcon 900", type: "Fixed-wing" },
  FA7X: { name: "DASSAULT Falcon 7X", type: "Fixed-wing" },
  DH8B: { name: "1996 DE HAVILLAND DHC-8-200 Dash 8", type: "Fixed-wing" },
  AS65: { name: "Eurocopter MH-65D Dolphin", type: "Rotary-wing" },
  C5M: { name: "Lockheed C-5M Super Galaxy", type: "Fixed-wing" },
  H60: { name: "SIKORSKY UH-60 Black Hawk", type: "Rotary-wing" },
  C560: { name: "CESSNA 560 Citation Ultra", type: "Fixed-wing" },
  D328: { name: "DORNIER 328", type: "Fixed-wing" },
  TEX2: { name: "Raytheon T-6A Texan II", type: "Fixed-wing" },
  HAWK: { name: "BRITISH AEROSPACE T-45 Goshawk", type: "Fixed-wing" },
  C27J: { name: "Alenia C-27J Spartan", type: "Fixed-wing" },
  A119: { name: "AGUSTA AW-119 Koala", type: "Rotary-wing" },
  C30J: { name: "LOCKHEED MARTIN C-130J Super Hercules", type: "Fixed-wing" },
  BE9L: { name: "BEECH 90 King Air", type: "Fixed-wing" },
  BE20: { name: "BEECH 200 Super King Air", type: "Fixed-wing" },
  T38: { name: "NORTHROP T-38 Talon", type: "Fixed-wing" },
  TUCA: { name: "EMBRAER EMB-312 Tucano", type: "Fixed-wing" },
  A149: { name: "AGUSTA AW-149", type: "Rotary-wing" },
  H160: { name: "AIRBUS HELICOPTERS H-160", type: "Rotary-wing" },
  E550: { name: "EMBRAER EMB-550 Praetor 600", type: "Fixed-wing" },
  C208: { name: "CESSNA 208 Caravan", type: "Fixed-wing" },
  E35L: { name: "EMBRAER EMB-135 Legacy", type: "Fixed-wing" },
  B737: { name: "BOEING 737-700", type: "Fixed-wing" },
  C172: { name: "1970 CESSNA 172 Skyhawk", type: "Fixed-wing" },
  V22: { name: "BELL-BOEING V-22 Osprey", type: "Fixed-wing" },
  LJ35: { name: "LEARJET 35", type: "Fixed-wing" },
  A21N: { name: "AIRBUS A-321neo", type: "Fixed-wing" },
  C25A: { name: "CESSNA 525A Citation CJ2", type: "Fixed-wing" },
  AT45: { name: "ATR-42-500", type: "Fixed-wing" },
  CP23: { name: "MUDRY CAP-230/1/2", type: "Fixed-wing" },
  H53S: { name: "SIKORSKY CH-53 Super Stallion", type: "Rotary-wing" },
  TBM7: { name: "SOCATA TBM-700A/B/C", type: "Fixed-wing" },
  D228: { name: "DORNIER 228", type: "Fixed-wing" },
  UH1Y: { name: "BELL UH-1Y", type: "Rotary-wing" },
  B412: { name: "BELL 412", type: "Rotary-wing" },
  BTB2: { name: "BAYKAR TB-2", type: "Fixed-wing" },
  GLF4: { name: "GULFSTREAM 4", type: "Fixed-wing" },
  PC21: { name: "PILATUS PC-21", type: "Fixed-wing" },
  DHC6: { name: "DE HAVILLAND DHC-6 Twin Otter", type: "Fixed-wing" },
  SW4: { name: "Fairchild C-26D Metro III", type: "Fixed-wing" },
  B190: { name: "BEECH 1900", type: "Fixed-wing" },
  B788: { name: "BOEING 787-8 Dreamliner", type: "Fixed-wing" },
  S92: { name: "SIKORSKY S-92 Helibus", type: "Rotary-wing" },
  B212: { name: "BELL 212", type: "Rotary-wing" },
  SR20: { name: "Cirrus T-53A Kaydet II", type: "Fixed-wing" },
  Q4: { name: "NORTHROP GRUMMAN RQ-4 Global Hawk", type: "Fixed-wing" },
  M28: { name: "PZL-MIELEC M-28 Skytruck", type: "Fixed-wing" },
  W3: { name: "PZL-SWIDNIK W-3", type: "Rotary-wing" },
  MI8: { name: "MIL Mi-8/9/17/19/171/172", type: "Rotary-wing" },
  E390: { name: "EMBRAER EMB-390", type: "Fixed-wing" },
  E3CF: { name: "BOEING E-3 Sentry (CFM56)", type: "Fixed-wing" },
  B703: { name: "BOEING 707-300", type: "Fixed-wing" },
  A319: { name: "AIRBUS A-319", type: "Fixed-wing" },
  IL62: { name: "ILYUSHIN Il-62", type: "Fixed-wing" },
  PC12: { name: "PILATUS PC-12", type: "Fixed-wing" },
  L410: { name: "LET L-410 Turbolet", type: "Fixed-wing" },
  H25B: { name: "HAWKER BEECHCRAFT Hawker 750/850", type: "Fixed-wing" },
  E190: { name: "EMBRAER ERJ-190-100", type: "Fixed-wing" },
  CN35: { name: "CASA HC-144A Ocean Sentry", type: "Fixed-wing" },
  AT43: { name: "ATR-42-300", type: "Fixed-wing" },
  C650: { name: "CESSNA 650 Citation", type: "Fixed-wing" },
  PUMA: { name: "AEROSPATIALE SA-330 Puma", type: "Rotary-wing" },
  T204: { name: "TUPOLEV Tu-204/214/224/234", type: "Fixed-wing" },
  C501: { name: "CESSNA 501 Citation 1SP", type: "Fixed-wing" },
  F260: { name: "AERMACCHI SF-260", type: "Fixed-wing" },
  KC2: { name: "KAWASAKI C-2", type: "Fixed-wing" },
  E737: { name: "BOEING 737-700 AEWC", type: "Fixed-wing" },
  AS32: { name: "AEROSPATIALE AS-332 Super Puma", type: "Rotary-wing" },
};

export function IdentifyCountry(hexCode: string) {
  return countryCodes[hexCode.substring(0, 3).toUpperCase()] || "Unknown";
}

export function IdentifyAircraft(type: string) {
  return aircraftTypes[type] || { name: "Unknown", type: "Unknown" };
}
