type CountryMapping = {
  [key: string]: string;
};

type AircraftTypes = "Fixed-wing" | "Rotary-wing" | "Tiltrotor" | "Unknown";

type AircraftMapping = {
  [key: string]: { name: string; type: AircraftTypes; manufacturer: string };
};

const countryCodes: CountryMapping = {
  "39A": "France",
  "3B9": "France",
  "3BF": "France",
  "3B7": "France",
  "3AA": "France",
  "43C": "United Kingdom",
  "400": "United Kingdom",
  "407": "United Kingdom",
  "3E8": "Germany",
  "3EA": "Germany",
  "3EB": "Germany",
  "3F4": "Germany",
  "3F7": "Germany",
  "3FA": "Germany",
  "3FB": "Germany",
  "3E9": "Germany",
  "3F5": "Germany",
  "3F9": "Germany",
  "3F6": "Germany",
  "352": "Spain",
  "354": "Spain",
  "355": "Spain",
  "356": "Spain",
  "347": "Spain",
  "353": "Spain",
  "497": "Portugal",
  "449": "Belgium",
  "44F": "Belgium",
  "4A3": "Romania",
  "4B8": "Turkey",
  "4BA": "Turkey",
  "738": "Israel",
  "157": "Russia",
  "14F": "Russia",
  "153": "Russia",
  "155": "Russia",
  "4CA": "Ireland",
  AE0: "USA",
  ADF: "USA",
  A42: "USA",
  A89: "USA",
  A9D: "USA",
  AAB: "USA",
  AB3: "USA",
  ABA: "USA",
  AF4: "USA",
  "320": "Italy",
  "33F": "Italy",
  ADD: "USA",
  AE7: "USA",
  AE6: "USA",
  AE5: "USA",
  AED: "USA",
  AE4: "USA",
  AE2: "USA",
  AE1: "USA",
  A96: "USA",
  A8B: "USA",
  A6D: "USA",
  A36: "USA",
  A2E: "USA",
  A09: "USA",
  AAA: "USA",
  AA7: "USA",
  ADC: "USA",
  A9A: "USA",
  "800": "India",
  "70C": "Oman",
  "706": "Kuwait",
  "894": "Bahrain",
  "505": "Slovakia",
  "451": "Bulgaria",
  "498": "Czechia",
  "481": "Netherlands",
  "480": "Netherlands",
  "485": "NetherLands",
  "0AC": "Columbia",
  "0D0": "Mexico",
  "0D8": "Venezuela",
  E84: "Ecuador",
  E49: "Brazil",
  E47: "Brazil",
  E48: "Brazil",
  E40: "Brazil",
  E14: "Argentina",
  C2C: "Canada",
  C2B: "Canada",
  C2A: "Canada",
  "896": "United Arab Emirates",
  "710": "Saudi Arabia",
  "711": "Saudi Arabia",
  "717": "Saudi Arabia",
  "732": "Iran",
  "50F": "Ukraine",
  "506": "Slovenia",
  "4CC": "Iceland",
  "4B7": "Switzerland",
  "4A8": "Sweden",
  "48D": "Poland",
  "478": "Norway",
  "477": "Hungary",
  "467": "Finland",
  "447": "Austria",
  "0C4": "Dominican Republic",
  "0B4": "Guatemala",
  "090": "Angola",
  "06A": "Qatar",
  "45F": "Denmark",
  "020": "Morocco",
  "4D0": "Luxembourg",
  "044": "Ghana",
  "743": "Jordan",
  E88: "Paraguay",
  "0C2": "Panama",
  "0BA": "Honduras",
  "8A0": "Indonesia",
  E20: "Argentina",
  "516": "Montenegro",
  "880": "Thailand",
  "883": "Thailand",
  "881": "Thailand",
  "884": "Thailand",
  "7CF": "Australia",
  C87: "New Zealand",
  "010": "Egypt",
  "750": "Malaysia",
  "503": "Lithuania",
  "094": "Benin",
  E90: "Uruguay",
  468: "Greece",
  "758": "Philippines",
  "87C": "Japan",
  "762": "Pakistan",
  "507": "Uzbekistan",

  // "34": "Spain",
};

const aircraftTypes: AircraftMapping = {
  EUFI: {
    name: "EUROFIGHTER 2000",
    type: "Fixed-wing",
    manufacturer: "EUROFIGHTER",
  },
  B350: {
    name: "Super King Air 350",
    type: "Fixed-wing",
    manufacturer: "BEECHCRAFT",
  },
  K35R: {
    name: "KC-135R/T Stratotanker",
    type: "Fixed-wing",
    manufacturer: "BOEING",
  },
  E50P: {
    name: "EMB-500 Phenom 100",
    type: "Fixed-wing",
    manufacturer: "EMBRAER",
  },
  PC9: { name: "PC-9 Hudournik", type: "Fixed-wing", manufacturer: "PILATUS" },
  EC45: {
    name: "EC-145",
    type: "Rotary-wing",
    manufacturer: "AIRBUS HELICOPTERS",
  },
  EH10: {
    name: "EH-101 Merlin",
    type: "Rotary-wing",
    manufacturer: "AGUSTA WESTLAND",
  },
  A400: { name: "A-400M Atlas", type: "Fixed-wing", manufacturer: "AIRBUS" },
  H64: {
    name: "AH-64 Apache",
    type: "Rotary-wing",
    manufacturer: "MCDONNELL DOUGLAS",
  },
  LYNX: {
    name: "AW-159 Super Lynx",
    type: "Rotary-wing",
    manufacturer: "AGUSTAWESTLAND",
  },
  B52: {
    name: "B-52H Stratofortress",
    type: "Fixed-wing",
    manufacturer: "Boeing",
  },
  G12T: { name: "G-120TP", type: "Fixed-wing", manufacturer: "GROB" },
  H47: {
    name: "CH-47 Chinook",
    type: "Rotary-wing",
    manufacturer: "BOEING-VERTOL",
  },
  C17: {
    name: "C-17A Globemaster III",
    type: "Fixed-wing",
    manufacturer: "Boeing",
  },
  C295: { name: "C-295 Persuader", type: "Fixed-wing", manufacturer: "CASA" },
  CL60: {
    name: "CL-600 Challenger",
    type: "Fixed-wing",
    manufacturer: "BOMBARDIER",
  },
  C130: {
    name: "C-130 Hercules",
    type: "Fixed-wing",
    manufacturer: "LOCKHEED",
  },
  IL76: { name: "Il-76/82", type: "Fixed-wing", manufacturer: "ILYUSHIN" },
  GLF5: {
    name: "Gulfstream 5",
    type: "Fixed-wing",
    manufacturer: "GULFSTREAM",
  },
  TWR: { name: "TWR", type: "Fixed-wing", manufacturer: "" },
  A332: { name: "A-330-200", type: "Fixed-wing", manufacturer: "AIRBUS" },
  A139: { name: "AW-139", type: "Rotary-wing", manufacturer: "AGUSTA" },
  E3TF: {
    name: "E-3 Sentry (TF33)",
    type: "Fixed-wing",
    manufacturer: "BOEING",
  },
  P8: { name: "P-8 Poseidon", type: "Fixed-wing", manufacturer: "BOEING" },
  AT76: { name: "ATR-72-600", type: "Fixed-wing", manufacturer: "ATR" },
  R135: {
    name: "RC-135S Cobra Ball",
    type: "Fixed-wing",
    manufacturer: "Boeing",
  },
  B762: { name: "767-200", type: "Fixed-wing", manufacturer: "BOEING" },
  B77W: { name: "777-300ER", type: "Fixed-wing", manufacturer: "BOEING" },
  A148: { name: "An-148", type: "Fixed-wing", manufacturer: "ANTONOV" },
  EC35: {
    name: "EC-135/635",
    type: "Rotary-wing",
    manufacturer: "AIRBUS HELICOPTERS",
  },
  GLEX: {
    name: "BD-700 Global 6000/6500",
    type: "Fixed-wing",
    manufacturer: "BOMBARDIER",
  },
  F900: { name: "Falcon 900", type: "Fixed-wing", manufacturer: "DASSAULT" },
  FA7X: { name: "Falcon 7X", type: "Fixed-wing", manufacturer: "DASSAULT" },
  DH8B: {
    name: "DHC-8-200 Dash 8",
    type: "Fixed-wing",
    manufacturer: "DE HAVILLAND",
  },
  AS65: {
    name: "MH-65D Dolphin",
    type: "Rotary-wing",
    manufacturer: "Eurocopter",
  },
  C5M: {
    name: "C-5M Super Galaxy",
    type: "Fixed-wing",
    manufacturer: "Lockheed",
  },
  H60: {
    name: "UH-60 Black Hawk",
    type: "Rotary-wing",
    manufacturer: "SIKORSKY",
  },
  C560: {
    name: "560 Citation Ultra",
    type: "Fixed-wing",
    manufacturer: "CESSNA",
  },
  D328: { name: "328", type: "Fixed-wing", manufacturer: "DORNIER" },
  TEX2: { name: "T-6A Texan II", type: "Fixed-wing", manufacturer: "Raytheon" },
  HAWK: {
    name: "T-45 Goshawk",
    type: "Fixed-wing",
    manufacturer: "BRITISH AEROSPACE",
  },
  C27J: { name: "C-27J Spartan", type: "Fixed-wing", manufacturer: "Alenia" },
  A119: { name: "AW-119 Koala", type: "Rotary-wing", manufacturer: "AGUSTA" },
  C30J: {
    name: "C-130J Super Hercules",
    type: "Fixed-wing",
    manufacturer: "LOCKHEED MARTIN",
  },
  BE9L: { name: "90 King Air", type: "Fixed-wing", manufacturer: "BEECH" },
  BE20: {
    name: "200 Super King Air",
    type: "Fixed-wing",
    manufacturer: "BEECH",
  },
  T38: { name: "T-38 Talon", type: "Fixed-wing", manufacturer: "NORTHROP" },
  TUCA: { name: "EMB-312 Tucano", type: "Fixed-wing", manufacturer: "EMBRAER" },
  A149: { name: "AW-149", type: "Rotary-wing", manufacturer: "AGUSTA" },
  H160: {
    name: "H-160",
    type: "Rotary-wing",
    manufacturer: "AIRBUS HELICOPTERS",
  },
  E550: {
    name: "EMB-550 Praetor 600",
    type: "Fixed-wing",
    manufacturer: "EMBRAER",
  },
  C208: { name: "208 Caravan", type: "Fixed-wing", manufacturer: "CESSNA" },
  E35L: { name: "EMB-135 Legacy", type: "Fixed-wing", manufacturer: "EMBRAER" },
  B737: { name: "737-700", type: "Fixed-wing", manufacturer: "BOEING" },
  C172: { name: "172 Skyhawk", type: "Fixed-wing", manufacturer: "CESSNA" },
  V22: { name: "V-22 Osprey", type: "Tiltrotor", manufacturer: "BELL-BOEING" },
  LJ35: { name: "35", type: "Fixed-wing", manufacturer: "LEARJET" },
  A21N: { name: "A-321neo", type: "Fixed-wing", manufacturer: "AIRBUS" },
  C25A: {
    name: "525A Citation CJ2",
    type: "Fixed-wing",
    manufacturer: "CESSNA",
  },
  AT45: { name: "ATR-42-500", type: "Fixed-wing", manufacturer: "ATR" },
  CP23: { name: "CAP-230/1/2", type: "Fixed-wing", manufacturer: "MUDRY" },
  H53S: {
    name: "CH-53 Super Stallion",
    type: "Rotary-wing",
    manufacturer: "SIKORSKY",
  },
  TBM7: { name: "TBM-700A/B/C", type: "Fixed-wing", manufacturer: "SOCATA" },
  D228: { name: "228", type: "Fixed-wing", manufacturer: "DORNIER" },
  UH1Y: { name: "UH-1Y", type: "Rotary-wing", manufacturer: "BELL" },
  B412: { name: "412", type: "Rotary-wing", manufacturer: "BELL" },
  BTB2: { name: "TB-2", type: "Fixed-wing", manufacturer: "BAYKAR" },
  GLF4: {
    name: "Gulfstream 4",
    type: "Fixed-wing",
    manufacturer: "GULFSTREAM",
  },
  PC21: { name: "PC-21", type: "Fixed-wing", manufacturer: "PILATUS" },
  DHC6: {
    name: "DHC-6 Twin Otter",
    type: "Fixed-wing",
    manufacturer: "DE HAVILLAND",
  },
  SW4: {
    name: "C-26D Metro III",
    type: "Fixed-wing",
    manufacturer: "Fairchild",
  },
  B190: { name: "1900", type: "Fixed-wing", manufacturer: "BEECH" },
  B788: {
    name: "787-8 Dreamliner",
    type: "Fixed-wing",
    manufacturer: "BOEING",
  },
  S92: { name: "S-92 Helibus", type: "Rotary-wing", manufacturer: "SIKORSKY" },
  B212: { name: "212", type: "Rotary-wing", manufacturer: "BELL" },
  SR20: { name: "T-53A Kaydet II", type: "Fixed-wing", manufacturer: "Cirrus" },
  Q4: {
    name: "RQ-4 Global Hawk",
    type: "Fixed-wing",
    manufacturer: "NORTHROP GRUMMAN",
  },
  M28: {
    name: "M-28 Skytruck",
    type: "Fixed-wing",
    manufacturer: "PZL-MIELEC",
  },
  W3: { name: "W-3", type: "Rotary-wing", manufacturer: "PZL-SWIDNIK" },
  MI8: {
    name: "Mi-8/9/17/19/171/172",
    type: "Rotary-wing",
    manufacturer: "MIL",
  },
  E390: { name: "EMB-390", type: "Fixed-wing", manufacturer: "EMBRAER" },
  E3CF: {
    name: "E-3 Sentry (CFM56)",
    type: "Fixed-wing",
    manufacturer: "BOEING",
  },
  B703: { name: "707-300", type: "Fixed-wing", manufacturer: "BOEING" },
  A319: { name: "A-319", type: "Fixed-wing", manufacturer: "AIRBUS" },
  IL62: { name: "Il-62", type: "Fixed-wing", manufacturer: "ILYUSHIN" },
  PC12: { name: "PC-12", type: "Fixed-wing", manufacturer: "PILATUS" },
  L410: { name: "L-410 Turbolet", type: "Fixed-wing", manufacturer: "LET" },
  H25B: {
    name: "Hawker 750/850",
    type: "Fixed-wing",
    manufacturer: "HAWKER BEECHCRAFT",
  },
  E190: { name: "ERJ-190-100", type: "Fixed-wing", manufacturer: "EMBRAER" },
  CN35: {
    name: "HC-144A Ocean Sentry",
    type: "Fixed-wing",
    manufacturer: "CASA",
  },
  AT43: { name: "ATR-42-300", type: "Fixed-wing", manufacturer: "ATR" },
  C650: { name: "650 Citation", type: "Fixed-wing", manufacturer: "CESSNA" },
  PUMA: {
    name: "SA-330 Puma",
    type: "Rotary-wing",
    manufacturer: "AEROSPATIALE",
  },
  T204: {
    name: "Tu-204/214/224/234",
    type: "Fixed-wing",
    manufacturer: "TUPOLEV",
  },
  C501: {
    name: "501 Citation 1SP",
    type: "Fixed-wing",
    manufacturer: "CESSNA",
  },
  F260: { name: "SF-260", type: "Fixed-wing", manufacturer: "AERMACCHI" },
  KC2: { name: "C-2", type: "Fixed-wing", manufacturer: "KAWASAKI" },
  E737: { name: "737-700 AEWC", type: "Fixed-wing", manufacturer: "BOEING" },
  AS32: {
    name: "AS-332 Super Puma",
    type: "Rotary-wing",
    manufacturer: "AEROSPATIALE",
  },
  B738: { name: "737-800", type: "Fixed-wing", manufacturer: "BOEING" },
  B773: { name: "777-300", type: "Fixed-wing", manufacturer: "BOEING" },
  ATLA: { name: "Atlantic", type: "Fixed-wing", manufacturer: "BREGUET" },
  E314: {
    name: "EMB-314 Super Tucano",
    type: "Fixed-wing",
    manufacturer: "EMBRAER",
  },
  B38M: { name: "737 MAX 8", type: "Fixed-wing", manufacturer: "BOEING" },
  SF34: { name: "340", type: "Fixed-wing", manufacturer: "SAAB" },
  G115: { name: "G-115", type: "Fixed-wing", manufacturer: "GROB" },
  AN26: { name: "An-26", type: "Fixed-wing", manufacturer: "ANTONOV" },
  GLF6: { name: "G650", type: "Fixed-wing", manufacturer: "GULFSTREAM" },
  B752: { name: "757-200", type: "Fixed-wing", manufacturer: "BOEING" },
  IL96: { name: "Il-96", type: "Fixed-wing", manufacturer: "ILYUSHIN" },
  PC6T: {
    name: "PC-6 Turbo-Porter",
    type: "Fixed-wing",
    manufacturer: "PILATUS",
  },
  E121: { name: "EMB-121 Xingu", type: "Fixed-wing", manufacturer: "EMBRAER" },
  E145: { name: "ERJ-145", type: "Fixed-wing", manufacturer: "EMBRAER" },
  F5: { name: "F-5 Tiger 2", type: "Fixed-wing", manufacturer: "NORTHROP" },
  ASTR: {
    name: "Gulfstream G100",
    type: "Fixed-wing",
    manufacturer: "GULFSTREAM AEROSPACE",
  },
  A359: { name: "A-350-900", type: "Fixed-wing", manufacturer: "AIRBUS" },
  F100: { name: "FOKKER 100", type: "Fixed-wing", manufacturer: "FOKKER" },
  EN48: { name: "TH-28", type: "Rotary-wing", manufacturer: "ENSTROM" },
  B06: { name: "206 JetRanger", type: "Rotary-wing", manufacturer: "BELL" },
  PC7: { name: "PC-7 Astr", type: "Fixed-wing", manufacturer: "PILATUS" },
  P180: { name: "P-180 Avanti", type: "Fixed-wing", manufacturer: "PIAGGIO" },
  AS50: {
    name: "AS-350 Ecureuil",
    type: "Rotary-wing",
    manufacturer: "AEROSPATIALE",
  },
  HRON: { name: "Heron Drone", type: "Fixed-wing", manufacturer: "IAI" },
  C68A: {
    name: "680 Citation Latitude",
    type: "Fixed-wing",
    manufacturer: "CESSNA",
  },
  F15: {
    name: "F-15 Eagle",
    type: "Fixed-wing",
    manufacturer: "MCDONNELL-DOUGLAS",
  },
};

export function IdentifyCountry(hexCode: string) {
  return countryCodes[hexCode.substring(0, 3).toUpperCase()] || "Unknown";
}

export function IdentifyAircraft(type: string) {
  return aircraftTypes[type] || { name: "Unknown", type: "Unknown" };
}
